source 'https://github.com/CocoaPods/Specs.git'
platform :ios, '9.0'

target 'Bingefish' do
  # Comment this line if you're not using Swift and don't want to use dynamic frameworks
  use_frameworks!

  # Pods for Bingefish
  pod 'Alamofire', '~> 3.4'
  pod 'AlamofireImage', '~> 2.0'
  pod 'Fabric'
  pod 'Crashlytics'

  target 'BingefishTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'BingefishUITests' do
    inherit! :search_paths
    # Pods for testing
  end

end
